import 'package:flutter/material.dart';

const kGreenColor = Color(0xFF0A9550);

const List<String> kfupm_majors = [
  'Select Your Current Major',
  'Petroleum Engineering',
  'Architectural Engineering',
  'Accounting',
  'Actuarial Science and Financial Mathematics',
  'Aerospace',
  'Applied Aerospace Engineering',
  'Applied Chemical Engineering',
  'Applied Civil Engineering',
  'Applied Electrical Engineering',
  'Applied Mechanical Engineering',
  'Architecture',
  'Chemical Engineering',
  'Chemistry',
  'City Planning',
  'Civil Engineering',
  'Computer Engineering',
  'Computer Science',
  'Control and Instrumentation Systems Engineering (CISE)',
  'Electrical Engineering',
  'Finance',
  'Geology',
  'Geophysics',
  'Industrial and Systems Engineering (ISE)',
  'Management',
  'Management Information Systems',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Physics',
  'Software Engineering',
  'Statistics',
  'Graduate',
  'Faculty Member',
  'Others',
];

const List<String> eventTypes = [
  'Select Type',
  'Short Course',
  'Workshop',
  'Sport',
  'Festival',
  'Exam',
  'Other',
];
