// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQOgfSqmtTC1Um46JJRaZ74ZDj55PI_A',
    appId: '1:634999464299:web:d963fd72c6e5e31269ec2e',
    messagingSenderId: '634999464299',
    projectId: 'ccevents-5dd07',
    authDomain: 'ccevents-5dd07.firebaseapp.com',
    databaseURL: 'https://ccevents-5dd07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ccevents-5dd07.appspot.com',
    measurementId: 'G-5CY9VE3P9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaRNc9-JBC6eKlsYIF5DFRf0IwPLJhjcY',
    appId: '1:634999464299:android:8dbd8d2803ef0c5f69ec2e',
    messagingSenderId: '634999464299',
    projectId: 'ccevents-5dd07',
    databaseURL: 'https://ccevents-5dd07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ccevents-5dd07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr2jvjbeNNew088Emz_ZI1BZi6M5a33ao',
    appId: '1:634999464299:ios:6cd6caf93ffdb81069ec2e',
    messagingSenderId: '634999464299',
    projectId: 'ccevents-5dd07',
    databaseURL: 'https://ccevents-5dd07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ccevents-5dd07.appspot.com',
    iosBundleId: 'com.example.kfupmEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr2jvjbeNNew088Emz_ZI1BZi6M5a33ao',
    appId: '1:634999464299:ios:6cd6caf93ffdb81069ec2e',
    messagingSenderId: '634999464299',
    projectId: 'ccevents-5dd07',
    databaseURL: 'https://ccevents-5dd07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ccevents-5dd07.appspot.com',
    iosBundleId: 'com.example.kfupmEvents',
  );
}
